# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: "/nullpomino-parent"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      maven:
        patterns:
          - "*"


  - package-ecosystem: maven
    directory: "/nullpomino-core"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      # LWJGL 3 is API-incompatible with the LWJGL 2.x code base
      - dependency-name: "org.lwjgl.lwjgl:*"
        update-types:
          - "version-update:semver-major"
    groups:
      maven:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: "/nullpomino-run"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      maven:
        patterns:
          - "*"
